# Generated by Django 3.0.8 on 2020-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordext',
            name='text',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'choose record type'), ('d', 'daily')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recordext',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
