# Generated by Django 3.1.3 on 2020-11-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20201029_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordext',
            name='entity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
