# Generated by Django 3.1.3 on 2020-11-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_recordext_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordext',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
