# Generated by Django 3.1.3 on 2020-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20201103_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity', models.JSONField()),
            ],
            options={
                'verbose_name': 'RecordType',
                'verbose_name_plural': 'RecordTypes',
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='recordext',
            name='record_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='records_ext', to='diary.RecordType'),
        ),
    ]
