# Generated by Django 3.1.3 on 2020-11-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20201107_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('content', models.FileField(blank=True, null=True, upload_to='content/%Y/%m/%d/')),
                ('entity', models.JSONField(blank=True, null=True)),
                ('parents', models.ManyToManyField(related_name='_record_parents_+', to='diary.Record')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ('-create_date',),
            },
        ),
        migrations.DeleteModel(
            name='RecordExt',
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
