# Generated by Django 3.1.3 on 2020-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20201108_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='parents',
            field=models.ManyToManyField(blank=True, to='diary.Record'),
        ),
    ]
