# Generated by Django 3.1.3 on 2020-11-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20201108_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='title',
            new_name='name',
        ),
    ]
