# Generated by Django 3.1.3 on 2020-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20201109_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-edit_date',), 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.RemoveField(
            model_name='record',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='record',
            name='parents',
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('entity', models.JSONField()),
                ('record_type_parents', models.ManyToManyField(blank=True, to='diary.RecordType')),
                ('records', models.ManyToManyField(blank=True, related_name='children', to='diary.Record')),
            ],
            options={
                'verbose_name': 'RecordType',
                'verbose_name_plural': 'RecordTypes',
            },
        ),
    ]
