# Generated by Django 3.1.3 on 2020-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20201110_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractrecordtype',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='diary.RecordType'),
        ),
    ]
