# Generated by Django 3.1.3 on 2020-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20201110_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractrecordtype',
            name='children',
        ),
        migrations.AddField(
            model_name='recordtype',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='diary.AbstractRecordType'),
        ),
    ]
